### ISSUE TITLE
Custom Error message using passport Bearer

### ISSUE THREAD

**Issue by shajunr88** [ealeksandrov/NodeAPI#34]
In the below code even if I throw custom message for token expiry, it only sends 'Unauthorized' message instead of 'Token Expired'.

```js
return done(null, false, { message: 'Token expired' });
```

```js
passport.use(new BearerStrategy(
    function(accessToken, done) {
        AccessToken.findOne({ token: accessToken }, function(err, token) {

            if (err) { 
            	return done(err); 
            }

            if (!token) { 
            	return done(null, false); 
            }

            if( Math.round((Date.now()-token.created)/1000) > config.get('security:tokenLife') ) {

                AccessToken.remove({ token: accessToken }, function (err) {
                    if (err) {
                    	return done(err);
                    } 
                });

                return done(null, false, { message: 'Token expired' });
            }

            User.findById(token.userId, function(err, user) {
            
                if (err) { 
                	return done(err); 
                }

                if (!user) { 
                	return done(null, false, { message: 'Unknown user' }); 
                }

                var info = { scope: '*' };
                done(null, user, info);
            });
        });
    }
));
```

**Comment by ealeksandrov** [comment]
`HTTP 401` means `Unauthorized`.
It can be header-only response because all required info is stored in `WWW-Authenticate` header.

From [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2):

> The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.

> The client MAY repeat the request with a suitable Authorization header field (section 14.8). If the request already included Authorization credentials, then the 401 response indicates that authorization has been refused for those credentials.

> If the 401 response contains the same challenge as the prior response, and the user agent has already attempted authentication at least once, then the user SHOULD be presented the entity that was given in the response, since that entity might include relevant diagnostic information.

<img width="865" alt="screen shot 2018-03-01 at 18 46 14" src="https://user-images.githubusercontent.com/3132438/36854031-0b0af1b6-1d81-11e8-9b48-966861a63aff.png">


You can see that required header `WWW-Authenticate` is on its place:
```sh
WWW-Authenticate: Bearer realm="Users", error="invalid_token", error_description="Token expired"
```
There are applicable challenge, realm and error details that you're looking for. Just as RFC suggests.

But in RFC there is no restriction on what the body of the request can/cannot contain. So you can add it by yourself if needed. Example with [custom callback](http://www.passportjs.org/docs/authenticate/):

```js
// from default handling
router.get('/', passport.authenticate('bearer', { session: false }), function (req, res) {
    res.json({
    	msg: 'API is running'
    });
});

// to custom callback
router.get('/', customResponse, function (req, res) {
    res.json({
    	msg: 'API is running'
    });
});

function customResponse(req, res, next){
    passport.authenticate('bearer', { session: false }, function(err, user, info) {
        if (err) { return next(err); }
        if (!user) {
            return res.status(401)
            .set('WWW-Authenticate', info)
            .json({ message: info });
        }
        req.user = user;
        next();
    })(req, res, next);
}
```

Another possible option could be forwarding errors from Passport to Express: https://stackoverflow.com/a/34699181.

Related links:
1. https://stackoverflow.com/a/37551990 - answer about `HTTP 401` body
2. https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2 - RFC 2616 about `HTTP 401`
3. https://stackoverflow.com/a/35983944 - answer about custom callback
4. http://www.passportjs.org/docs/authenticate/ - docs on custom callback
5. https://stackoverflow.com/a/34699181 - answer about forwarding errors from Passport to Express
